# Generated by Django 4.0.4 on 2022-05-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[(0, 'Bullet'), (1, 'Food')], default=0, max_length=100),
        ),
    ]
